### ISSUE TITLE
Smaller images on homepage

### ISSUE THREAD

**Issue by theefer** [parcel-bundler/website#10]
The parcel-front@3x.png and parcel-back@3x.png images on https://parceljs.org/ amount to 1.1MB and  473KB. I would suggest looking into converting them to JPG with some medium-high quality, as that would easily let you reduce their size by ~10x, which would significantly speed up the loading time, especially on mobile.

**Comment by devongovett** [comment]
problem with jpg is that the images have transparency...

**Comment by DanielRuf** [comment]
PNGGauntlet, ImageOptim and sharp for Node.js can be used to optimize the file sizes.

**Comment by DanielRuf** [comment]
The perceived performance can be also optimized by using progressive images and we should use picture tags and provide different sizes. It makes no sense to load the same image on different viewports. Tracing / converting to SVG is also an option.

**Comment by devongovett** [comment]
Should be fixed by #58.

**Comment by DanielRuf** [comment]
Awesome. =)

Just wanted to prevent duplicate PRs. Would be good when contributors mention directly the issue which they try to solve with their PRs.
