### ISSUE TITLE
The Chinese document no Chinese?

### ISSUE THREAD

**Issue by gyt95** [parcel-bundler/website#1010]
https://v2.parceljs.cn/docs/

This document is written in Chinese, but it is all in English, which seems to be no different from the English official website. Why?

**Comment by devongovett** [comment]
See https://github.com/parcel-bundler/parcel/discussions/7805. We don't control that domain, and I'm not sure who does. But perhaps we could host an official Chinese translation at some point. We need to figure out the infrastructure to host translations in the repo/build pipeline.

**Comment by gyt95** [comment]
> See [parcel-bundler/parcel#7805](https://github.com/parcel-bundler/parcel/discussions/7805). We don't control that domain, and I'm not sure who does. But perhaps we could host an official Chinese translation at some point. We need to figure out the infrastructure to host translations in the repo/build pipeline.

Thanks. I thought this repo could answer my doubts, so I came here to ask questions again. It's pretty dumb that your documentation like this is .  speechless that the unknown domain name is pretending to be you guys.

**Comment by gyt95** [comment]
> See [parcel-bundler/parcel#7805](https://github.com/parcel-bundler/parcel/discussions/7805). We don't control that domain, and I'm not sure who does. But perhaps we could host an official Chinese translation at some point. We need to figure out the infrastructure to host translations in the repo/build pipeline.

I thought this repo could answer my doubts, so I came here to ask question again. Thank you for your answer, looking forward to the Chinese translation of your official documentation.
