### ISSUE TITLE
Plugin search results are not up to date

### ISSUE THREAD

**Issue by gxy5202** [parcel-bundler/website#1022]
### What information was incorrect, unhelpful, or incomplete?
When I select namer in Plugin type, some plugins on npm are not displayed, such as "parcel-namer-hashless".
![image](https://user-images.githubusercontent.com/37973863/163841877-e6279b26-3401-4816-bfb5-10b0c288c56b.png)

Could it be a search engine problem?

But just last month, all the plugins of npm can be displayed normally here.
Please see the image below
(Although the website "v2.parceljs.cn" is not controlled by us, the content is the same, I have tested this)
![263351623033307892](https://user-images.githubusercontent.com/37973863/163840778-d04104a4-4dee-4d4b-8c63-1734e5492a49.jpg)

**Comment by devongovett** [comment]
@DeMoorJasper do we have a contact at Algolia? Maybe something is misconfigured...

**Comment by DeMoorJasper** [comment]
@Haroenv helped me to setup the correct filters, so maybe he has some ideas as to why this happens?

It might be an issue with their npm search index though, seems like yarn's website is also out of date

**Comment by DeMoorJasper** [comment]
Actually seems like they're aware of it and working on it https://github.com/algolia/npm-search/issues/930

**Comment by Haroenv** [comment]
Sorry for the outdated data in the engine, we had to restore from an unfortunately old backup. If there's specific records I can restore quickly, I can do that before the index is back in sync.

**Comment by gxy5202** [comment]
@Haroenv @DeMoorJasper @devongovett Thank u for your explaination, hope this problem can be fixed

**Comment by Haroenv** [comment]
This should be fixed now!

**Comment by gxy5202** [comment]
> This should be fixed now!

maybe this issue should be closed
