### ISSUE TITLE
Add webassmbly and rust documentation

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/website#103]
Perhaps based on the examples I wrote for the announcement article: https://medium.com/@devongovett/parcel-v1-5-0-released-source-maps-webassembly-rust-and-more-3a6385e43b95

**Comment by Taym95** [comment]
Hi, in which section we should add webassembly and rust documentation?

**Comment by DeMoorJasper** [comment]
@Taym95 probably in here: https://parceljs.org/transforms.html

Although it would be very valuable as that file is getting ginormous to restructure the doc site as proposed here: #234
