### ISSUE TITLE
Add Configuration section with some `.parcelrc` examples

### ISSUE THREAD

**Issue by matronator** [parcel-bundler/website#1035]
Looking through the website, I had a really hard time finding any info about configuration. There isn't even any mention about `.parcelrc` file, let alone some examples, or the available options for it. There's some small mention in the [Parcel API](https://parceljs.org/features/parcel-api/) section, but I think it should have it's own section.

**Comment by devongovett** [comment]
https://parceljs.org/features/plugins/ ?

**Comment by matronator** [comment]
Oops, sorry. Why is it in the Plugins section, though?

**Comment by devongovett** [comment]
Because .parcelrc is for configuring Parcel plugins?

**Comment by matronator** [comment]
Oh. Where do I configure other options then? Like which files/folders to include/exclude, the output directory, etc.?

**Comment by devongovett** [comment]
https://parceljs.org/features/targets/
