### ISSUE TITLE
[Plugin Search page]Error 400 is reported for page request

### ISSUE THREAD

**Issue by gxy5202** [parcel-bundler/website#1042]
The Plugin Search page is invalid due to a request error
![Snipaste_2022-08-02_15-04-37](https://user-images.githubusercontent.com/37973863/182312900-80c84dc6-3ea3-4dcc-b117-8f76310b6001.png)

**Comment by devongovett** [comment]
Possibly related to something here https://github.com/parcel-bundler/website/blob/998749c68f098a90a2d2bcf9346bcae4fa204dbd/src/plugin-browser/hooks.js#L26

**Comment by gxy5202** [comment]
> Possibly related to something here
> 
> https://github.com/parcel-bundler/website/blob/998749c68f098a90a2d2bcf9346bcae4fa204dbd/src/plugin-browser/hooks.js#L26

I've open a PR to solve this problem
