### ISSUE TITLE
Recipe documentation says to install parcel-bundler, but that appears to be obsolete

### ISSUE THREAD

**Issue by ericbiewener** [parcel-bundler/website#1043]
The [Recipes](https://en.parceljs.org/recipes.html) documentation says to install `parcel-bundler`, but that appears to no longer be correct (and leads to confusing behavior because the `parcel` command still works but it's now executing the one from the old parcel-bundler package).

**Comment by mischnic** [comment]
That is correct, as noted in the header:

> Note: This page covers Parcel 1, the documentation for Parcel 2 is being worked on here: [v2.parceljs.org](https://v2.parceljs.org/)
