### ISSUE TITLE
Getting started suggests installing obsolete parcel-bundler

### ISSUE THREAD

**Issue by mkahvi** [parcel-bundler/website#1048]
As per title, the getting started documentation is suggesting you install the unsupported `parcel-bundler` instead of the current `parcel` package.

**Comment by devongovett** [comment]
Maybe you're looking at the v1 docs? The v2 site is here: https://parceljs.org/getting-started/webapp/

**Comment by mkahvi** [comment]
This: <https://en.parceljs.org/getting_started.html>

And yes, I guess it does mention with small text it's for v1 now that you mention it.

Tho speaking of which, the link in v1 docs to v2 docs appears broken.

**Comment by devongovett** [comment]
Yeah those are the v1 docs. See the banner at the top of the page.

**Comment by mkahvi** [comment]
I'll just close this as a mistake on my part.
