### ISSUE TITLE
Documentation for sourcemaps?

### ISSUE THREAD

**Issue by mindplay-dk** [parcel-bundler/website#110]
Looks like support for [source-maps](https://github.com/parcel-bundler/parcel/pull/506) just landed - is it documented?

**Comment by DeMoorJasper** [comment]
There is a PR for the disable source-map flag (#96), although source maps isn't available in production at the moment so it's on hold until that pr gets approved.
Documentation on current development source-maps is not available however.

**Comment by DeMoorJasper** [comment]
Fixed in #96
