### ISSUE TITLE
based on docs it's not clear if one could require scss from html or not

### ISSUE THREAD

**Issue by safareli** [parcel-bundler/website#155]
Based on current docs it's not clear if one could require scss from html or not:

> # CSS
> CSS assets can be imported from a JavaScript **or HTML** file ... In addition to plain CSS, other compile-to-CSS languages like LESS, **SASS**, and Stylus are also supported, and **work the same way**.
> 
> # [SCSS](https://parceljs.org/assets.html#scss)
> ... Once you have node-sass installed you can import **SCSS files from JavaScript files** ...

https://github.com/parcel-bundler/parcel/issues/1278#issuecomment-385949589

**Comment by isthatcentered** [comment]
Would adding a section at the top of the[ **assets**](https://en.parceljs.org/assets.html) page work (just before javascript)? 
Something like:

**Importing uncompiled assets directly from index.html**
If you link any file supported by parcel (JavaScript/Typescript/SCSS/...) in an `HTML` file Parcel will automatically process it for you.
Meaning, you can directly reference a `.ts` or `.scss` file in your `index.html` and it will just work.
(+ code example)

**Comment by DeMoorJasper** [comment]
If anyone wants to tackle this, now html has it's own page where this could end up in: https://en.parceljs.org/html.html#html

**Comment by andrew-anguiano** [comment]
@DeMoorJasper I took a shot at adding the requested info. Let me know if you want any changes!
