### ISSUE TITLE
Update (deploy) the web site

### ISSUE THREAD

**Issue by forresst** [parcel-bundler/website#163]
I notice that the changes I made are not applied on the site parceljs.org, should not an update be launched (deploy, "zeit now)?

Here is the list of changes that are not applied on the site:
* Fix typo first sylvainpolletvillard review parcel-bundler/website@3f84f95330a199c3226e170964b4974a7d23e9e4 (Commit on Apr 30, 2018)
* Update translation in french parcel-bundler/website@cb233a57b6a93c4c408da0555ea3b46179e5450a (Commit on May 5, 2018)
* Update translation in french  parcel-bundler/website@f69debe5d02f8160c2216e04d74f0ea5d85dd031 (Commit on May 18, 2018 )

**Comment by lex111** [comment]
It seems that the authors are don't care on this

**Comment by lex111** [comment]
ping @brandon93s

**Comment by lex111** [comment]
It's unfortunate that nobody cares about this problem, it lowers interest in Parcel, well, it's good that there is a Webpack!

**Comment by DeMoorJasper** [comment]
No need to spam this issue, it won’t get resolved faster this way. The only person who can resolve this is @devongovett 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by forresst** [comment]
The site is up to date. Thanks
