### ISSUE TITLE
docs: add section on module resolution

### ISSUE THREAD

**Issue by iamclaytonray** [parcel-bundler/website#184]
I am currently playing around with Parcel on a new React app I created. Almost everything I do in JavaScript, I do in TypeScript. With that being said, I take advantage of Module Resolution. I know that absolute paths/imports were finalized in the 1.7.0 release and in this  [PR](https://github.com/parcel-bundler/parcel/pull/850), but I'd like to document this.

I read some comments and while I can respect different perspectives, I know that for larger projects I work on, it's important to use absolute imports or the imports themselves get too deep/convoluted. Trying out the solution in the PR mentioned above, I do have absolute imports working but my IDE (VS Code) is going crazy with errors. This doesn't affect the actual app running but can be distracting when I am trying to debug. I think a new section on module resolution / absolute imports with Parcel can help developer experience and adoption with Parcel. (This was the biggest reason I didn't try Parcel. I just learned that this feature existed the other day.)

I can't commit to having this PR in an hour or even a week. I'd like to fully understand how everything works so I can provide some stellar docs for other people. If this sounds good to project maintainers, please let me know! Thanks for all the hard work, ladies and gents.

**Comment by iamclaytonray** [comment]
Actually, that was much easier than I thought it would be. So, I can add docs if/when this get approved. Thanks!

**Comment by DeMoorJasper** [comment]
Would be awesome if you could create a PR for this. (we haven't gotten around to documenting every new feature since 1.7.0 yet, see #132 ).

Every bit of help is very welcome.
