### ISSUE TITLE
Refactor website to use Vue.js

### ISSUE THREAD

**Issue by viktor-ku** [parcel-bundler/website#204]
Hi.

I noticed that pages are loading slowly event though website is not complex.

How about re-create it using Vue.js?

If this idea is fine then I can do it

**Comment by DeMoorJasper** [comment]
Vue.js would make it load slower, not faster by any means.

The current docs are static pages, nothing's faster than a static website

**Comment by viktor-ku** [comment]
Initial loading of the website, sure. 

But when you change pages it loads them every single time. Using SPAs it wouldn't be a problem
