### ISSUE TITLE
restructure documentation site

### ISSUE THREAD

**Issue by jthegedus** [parcel-bundler/website#234]
Hey, contributors, I would like to open discussion of restructuring the documentation.

Things I've liked about the current docs:
* concise
* clear distinction about terms

Things I would like to contribute to and see improved:
* separate usage from creating (eg plugins)
* describe the default features and how each OOTB tool is supported
* 0 config is great, but ultimately users still need to understand how it all works

I feel like the overall docs would benefit from a restructuring, namely a better separation of the user/creator information.

Here is a suggestion I have thought about while contributing over the last few days:

### nav headings with descriptions of topics

this is my idea of a restructure:

---

getting started
* quick start
  explaining simple setup, dev use & prod output
* assets & transforms
  explain what an asset & a transform are
  use an image to explain (make it shorter than existing Assets section)

features
* code splitting
* hot module reloading
* production bundling
* cli

out of the box support
* default asset types
  list of asset types, their associated file extension(s) and common tools they support. each item in the list links to a page for that asset type
* env vars
* module resolution
* using plugins

asset types
* ...asset-type item (ie: JavaScript, ReasonML...)
  what tool is used to support this (this matters when talking about feature support and improving on the asset's ecosystem within Parcel)
  the config files used by the underlying tool
  default transforms that apply to the asset
  embed some codesandbox.io examples maintained via https://github.com/parcel-bundler/examples

create
* how it works
* assets & parsers
* plugins
* packagers
* bundler api

EG

![parcel docs restructure idea](https://user-images.githubusercontent.com/20798510/44617543-7c1bc680-a8a7-11e8-9c1a-4ac0a96ea2ed.png)

This is just an idea, so feel free to turn it down, but please note that I will happily do this work, it's a request to contribute. I'm very passionate about documentation and figure what better way to learn the inner-workings of Parcel 😄

If you would like to see what or how I would structure some of the specific "asset types" pages content I'll happily write one up as a further example.

---

Other considerations alongside a restructure:

* search, as raised in #193, would make this much nicer to find information on say, [flow](https://flow.org/) which would be mentioned under the JavaScript page and not have it's own top-level page.
* need css for the left nav to scroll independently of the content.

**Comment by DeMoorJasper** [comment]
@jthegedus really like the idea. Pretty sure this would make it a lot easier to browse the docs and add some structure to it.

**Comment by jthegedus** [comment]
@Taym95 wow, thanks for tackling this! I got caught up moving houses and have been inactive for a few weeks. Cheers for getting this started!
