### ISSUE TITLE
'npm run build' fails on Windows 7

### ISSUE THREAD

**Issue by brian32768** [parcel-bundler/website#292]
Running in Cygwin GIT Bash,

```
$ npm run build

> parcel-website@1.0.0 build C:\Users\bwilson\source\repos\parcel-website
> ./build.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! parcel-website@1.0.0 build: `./build.sh`
npm ERR! Exit status 1
```

**Comment by forresst** [comment]
While waiting for a correction of the npm scripts to manage the use under windows, you can launch the following statement `.\build.sh` instead of `npm run build` :

```shell
$ .\build.sh
```

It will do exactly the same thing.

**Comment by theuves** [comment]
I have the same problem with MinGW on Windows 10.

***

https://github.com/parcel-bundler/website/blob/1b285804972343da1733ee1980922abcca36735c/package.json#L10

The `./build.sh` value couldn't be replaced by `bash ./build.sh` or `sh ./build.sh`?

With `bash` or `sh` command, the problem would be solved in Windows, but I don't know what would happen in other systems.
