### ISSUE TITLE
Asset types section in sidebar contains only dead links

### ISSUE THREAD

**Issue by CyberAP** [parcel-bundler/website#300]
If you go to [Javascript assets page](https://parceljs.org/javascript.html) you'll get this error:

```
Cannot GET /javascript.html
```

That happens to all of the asset types links.

That's because site now requires a language domain, which is not set if you're using default language.

So I guess `https://parceljs.org/getting_started.html` should always be `https://en.parceljs.org/getting_started.html`, where `en` is your current language.

**Comment by DeMoorJasper** [comment]
I'm not able to reproduce this, in what language does this happen?

**Comment by Taym95** [comment]
Yes because we changed the document structure, check the difference between English and Russian documentation.

**Comment by DeMoorJasper** [comment]
Seems to work fine to me, like @Taym95 mentioned the Russian docs are still using the old structure and are fairly outdated, so they have a couple pages that don't exist on english (most up-to-date) version and vice-versa

**Comment by Grawl** [comment]
For [`/ru`](https://ru.parceljs.org/getting_started.html), there is only HTML in resources:

![Screenshot_20200601_221619](https://user-images.githubusercontent.com/846774/83408250-aa9fdb80-a455-11ea-84d2-178bb5c28480.png)
