### ISSUE TITLE
Unable to view environmental variables page

### ISSUE THREAD

**Issue by feardarkness** [parcel-bundler/website#304]
Something seems wrong with the site

https://parceljs.org/env.html

![seleccion_153](https://user-images.githubusercontent.com/860571/48779139-51c28500-ecad-11e8-8fe4-aeb9626fdb07.png)

Everything else is fine, is just the environmental variables page.

![seleccion_154](https://user-images.githubusercontent.com/860571/48779942-12953380-ecaf-11e8-931f-c65191e68feb.png)

**Comment by Taym95** [comment]
Weird because the link works for me.

**Comment by feardarkness** [comment]
I just tried with a proxy and doesn't work

**Comment by feardarkness** [comment]
The problem is present in the spanish translation only

![seleccion_155](https://user-images.githubusercontent.com/860571/48781136-c7c8eb00-ecb1-11e8-876f-88680406e290.png)

**Comment by Taym95** [comment]
Hey @feardarkness,  the Spanish docs are still using the old structure and are fairly outdated, so they have a couple pages that don't exist on English (most up-to-date) version and vice-versa.

Check English doc and feel free to update the Spanish docs to the new structure :)

**Comment by feardarkness** [comment]
I can help translating, is there any guide to getting started?
