### ISSUE TITLE
Need docs for publishing a React component to NPM

### ISSUE THREAD

**Issue by vijayst** [parcel-bundler/website#306]
Need docs for publishing a React component to NPM. 

A react component has React as dependency. But I do not want to package React. At the same time, React needs to resolve to node_modules of the app in which the component is used. Some docs regarding NPM publishing, especially of React components will be helpful.

As an example, you can check [react-reducer-store](https://github.com/vijayst/react-store).

**Comment by mischnic** [comment]
> A react component has React as dependency. But I do not want to package React.

This is currently not possible, you can follow this issue: https://github.com/parcel-bundler/parcel/issues/144
