### ISSUE TITLE
including scss via npm doesn't twork

### ISSUE THREAD

**Issue by Dagge1** [parcel-bundler/website#310]
I installed sass and node-sass via npm but it shows error.. import "./xxx/bootstrap.scss" still doesn't work. I'm using it with Vue and I'm trying to use Bootstrap V4 scss via npm (I also installed JQuery and popper.js. It says 
"Cannot create property 'includePaths' on string 'scss/bootstrap.scss"

First I was delighted with parcel then I realized that it is neither simple nor configuration-free, so advantage over webpack suddenly dissappeared. It also didn't allow me to use Vue in dev mode, so I needed to use render: h => h(App) in Vue in order to make it work.

**Comment by Dagge1** [comment]
I found a solution which is a bit 'patchy' but works. In master js file include ordinary .css file which is in case of bootstrap like this:` import './node_modules/bootstrap/dist/css/bootstrap.css';`

Then install sass compiler, make it global, open another CLI (one for parcel, another for scss) and enter sass command that will watch all your changes to a .scss files and autmatically recompile it.

Something like: `sass --watch source.scss:destnation.css`

Now you will have both parcel and sass compiler run simultaneously and everything works fine (until parcel guys fix this problem in next version).

**Comment by DeMoorJasper** [comment]
An example project would help as this could be anything. Also this repo is for the docs only and this appears to be a code related issue

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
