### ISSUE TITLE
Document how to transpile packages from node_modules

### ISSUE THREAD

**Issue by garth** [parcel-bundler/website#312]
On the [transforms docs page](https://parceljs.org/transforms.html#third-party-modules) it says:

> "Configuration files (such as .babelrc) will not be applied to files inside third-party node_modules by _default_."

But other than info for mono-repo's it doesn't say how to do this. This is important when targeting specific browsers and 3rd party modules have not been transpiled for those targets.

**Comment by DeMoorJasper** [comment]
Like the docs says it’s impossible to do this. However node modules do get transpiled down to the specified browser/node target

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by garth** [comment]
Sure node_modules should only contain "standard js" but that is relative term. For example if you still have to support IE9 then it becomes necessary to transpile node_modules to be sure that there are no objects with reserved keywords as property names.

I ran into this issue a few times, and it seems that the only way to fix is to go back to webpack where node_modules can configured to be included :-(

There should be a flag or some way to do this with parcel?

**Comment by kubenstein** [comment]
My case is a 3rd party published package - Vuex, [relies on `Promise` to be available](https://github.com/vuejs/vuex/blob/2257036aaa020b96eb52f507b65b1c292a6732e1/src/store.js#L19). Generally I use babel-runtime to patch all missing functionalities across a project yet not to pollute global scope with polyfills. [core-js provides non-polyfill version of Promise](https://github.com/zloirock/core-js/tree/master/packages/core-js-pure) that I could use. Unfortunately its not possible with current parcel configuration options. I think it may be a valid case to reconsider allowing users to transpile published packages.
