### ISSUE TITLE
"Getting Started" install global vs local

### ISSUE THREAD

**Issue by clickbox** [parcel-bundler/website#313]
Moments ago in my bedroom while listening to Michael Cera's cover of "Clay Pigeons" I begin to unwind from my day. I ask myself what is bothering me and eventually come to the conclusion that my lack of a easy bundler for my beloved ES6 army of modules was the root. Webpack was hurting my mojo.

Time to try parcel, zero config sounded like the medicine I was in search of. Let's just whip up a quick project and play with this new tool sent to calm quelth my inner woes.

 "yarn global add parcel-bundler"? stopped me dead in my tracks. A million question... Does it have to be? When was the last time I installed global? What version of node am I on right now I was hacking some angularJS project earlier... there's a global argument for yarn? How am I going to use this demo at work tomorrow if I don't save my dependency? Isn't that kind of presumptuous? I'm just going to go sleep.
 I just wanted a quick hot bundle, maybe tomorrow.

**Comment by DeMoorJasper** [comment]
Global install in the getting started guide was a decision that was made a little while back.

The docs however cover installing as a dependency in a project as well which is the best option in most cases where you have a team and want reproducable results https://parceljs.org/getting_started.html#adding-parcel-to-your-project
