### ISSUE TITLE
Allow rust files to re-use Rust build artifacts

### ISSUE THREAD

**Issue by jjpe** [parcel-bundler/website#317]
I'm trying to get parcel to work for my rust/wasm project.

I'm first built the project with `wasm-bindgen`, and then I ran `parcel --log-level 4 index.html`.
TBH I expected that it would just re-use the build artifacts but instead `parcel` seems intent on doing everything itself.

As build times for the rust code are roughly 11 minutes, this is not a trivial issue, and in turn it unfortunately falsifies the "blazing fast" part of the claim that it is a `Blazing fast, zero configuration web application bundler`. I understand that the tool itself is likely fast, but if a part of the build process is not, then using the tool as a whole is not fast either.

Therefore, could the project be updated to re-use pre-existing build artifacts?

**Comment by DeMoorJasper** [comment]
This is the repo for the website, so only docs related things should be discussed and implemented here.

I'll close this. Feel free to open this issue in the code repo: https://github.com/parcel-bundler/parcel
