### ISSUE TITLE
Document Development Debugging Approach

### ISSUE THREAD

**Issue by evanleck** [parcel-bundler/website#321]
The [Production](https://parceljs.org/production.html) page mentions development-only debugging used in libraries.

>  Large libraries like React have development only debugging features which are disabled by setting this environment variable, which results in smaller and faster builds for production.

I'd love to see the implementation of something like that documented so users of Parcel could take the same approach. If you're familiar with it and can give me a quick explanation or can drop me a link I'm happy to create a PR.

Thanks!

**Comment by DeMoorJasper** [comment]
I'm not sure what you mean but I could try to explain as far as I understand the question.

So React (and pretty much all libraries with develop specific code) have their development specific code wrapped around an if that checks for the `NODE_ENV` variable. This gets removed out of production builds by the minifier.

small example:
```Javascript
if (process.env.NODE_ENV === 'development') { // alternatively use process.env.NODE_ENV !== 'production' if this should run in staging, ...
  // This is the development environment, include some advanced dev thing here
  const devtools = require('./dev/tools');
}

// code that should always run...
```

**Comment by evanleck** [comment]
That's exactly what I was looking for! I thought that was how to do that but I wanted to make sure. Do you agree that it'd be worth spelling that out somewhere in the docs? Does the production page seem like the right place if so?

**Comment by DeMoorJasper** [comment]
@evanleck Yes it would be amazing if you could add this to the docs. Production seems like the right place to put this
