### ISSUE TITLE
Possibly outdated information for log levels

### ISSUE THREAD

**Issue by lustoykov** [parcel-bundler/website#323]
Only log levels 1-3 are mentioned in the [API documentation](https://parceljs.org/api.html), as far as I'm aware they go [up to 5](https://github.com/parcel-bundler/parcel/blob/e110b16afafb56b9878fd179f98d9acd66745fed/src/cli.js#L61). Is this due to outdated docus or rather intentional?

**Comment by mischnic** [comment]
Also: the CLI page contains all 5 log levels, but doesn't mention that request for the dev server are logged with level >= 4.
