### ISSUE TITLE
Document how to increase the memory limit of node

### ISSUE THREAD

**Issue by holyjak** [parcel-bundler/website#342]
When I run node, I can increase its memory (±2GB by default on 64b) like this:

    node --max_old_space_size=4096  ...

However I have no idea how to do that when the command I run is `parcel` and could not find anything in the docs.

I would expect https://parceljs.org/cli.html to tell me how to do it.

Thanks!

**Comment by mischnic** [comment]
`npx --node-arg=what_you_want_to_set parcel ...` might work
