### ISSUE TITLE
List required version of node

### ISSUE THREAD

**Issue by BigBadaboom** [parcel-bundler/website#347]
I use node rarely. Today I tried to run parcel for a client project, and I was getting weird errors: (something like "./lib not found").
After Googling for a bit, I found a comment that Parcel requires Node 8+. 

I would suggest that should be prominently displayed somewhere in the docs (Getting started?), given that parcel doesn't work otherwise, and the Node 8 release was only 18 months ago.

**Comment by BigBadaboom** [comment]
Hmm... I just found https://github.com/parcel-bundler/parcel/issues/231, and its rejected patch to update the readme, so I guess this issue has little chance ... :-/

**Comment by DeMoorJasper** [comment]
@BigBadaboom Parcel supports Node 6+, might be an issue with a plugin?
