### ISSUE TITLE
Troubleshooting css HMR

### ISSUE THREAD

**Issue by LewisAndrewCampbell** [parcel-bundler/website#356]
I've run into a situation where editing the css doesn't trigger HMR, but editing the JS does. it seems like it's caching an old version. A discussion of when that happens and why could be helpful.

**Comment by mischnic** [comment]
If this issue is about Parcel in general and not the website https://parceljs.org, please open an bug issue with more details and a reproduction here: https://github.com/parcel-bundler/parcel/issues
