### ISSUE TITLE
Don't hash output names

### ISSUE THREAD

**Issue by telemac** [parcel-bundler/website#368]
Hello,
I use parcel to generate the web assets for an embedded system. the assets are embedded in a go binary so I need constant names for all the files. How can I achieve that with parcel ?
Thx for the great work.

**Comment by DeMoorJasper** [comment]
This is currently impossible with browsertarget if you’re targeting node it does not hash bundlenames `—target=node` however these bundles will usually not run in the browser

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by telemac** [comment]
Is this a feature that is planned to be added, say with a command line option ? Sadly it's mandatory in my workflow and I'd be really happy to use parcel. And yes, I generate for the browser.
Thx

**Comment by DeMoorJasper** [comment]
Parcel 2 will allow writing your own naming strategy, so it’s planned but not for Parcel 1

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by telemac** [comment]
Great. Thank you
