### ISSUE TITLE
Unclear how to use module resolution in SCSS files

### ISSUE THREAD

**Issue by ejwaibel** [parcel-bundler/website#370]
Need a way to use the `~` to point to npm packages SCSS

So, instead of having
 `@import "../../../node_modules/bootstrap/file.scss"`

I could just use
 `@import "~/bootstrap/file.scss"

**Comment by DeMoorJasper** [comment]
It should work if you use `@import "~bootstrap/file.scss"` as `~/` is absolute paths

**Comment by DeMoorJasper** [comment]
Also this is the docs repo, so if that didn't solve the issue reopen it here: https://github.com/parcel-bundler/parcel

**Comment by ejwaibel** [comment]
Ah, now I see the difference, thanks that worked!
