### ISSUE TITLE
Question about project translation

### ISSUE THREAD

**Issue by inductor** [parcel-bundler/website#376]
Hello,

I am working on the "actual" translation project into Japanese on this PR https://github.com/parcel-bundler/website/pull/374 after seeing https://github.com/parcel-bundler/website/issues/94 but I've got a few questions.

1. How do you add a new subdomain for a language? Is there an automation process or it has to be done based on some process/application?
2. Should the translation PR be for all pages, or is just a single page PR acceptable? If the latter was okay I could remove the WIP since I already translated the main page.

**Comment by devongovett** [comment]
Hi @inductor! Thanks for working on that.

1. The subdomains are listed in this file: https://github.com/parcel-bundler/website/blob/master/now.json. You can add one to the list and when merged to master, it will be automatically deployed.
2. Obviously we would like to have the whole site translated eventually, but if you wish to contribute only a single page, or break up your work, that's fine too.

**Comment by inductor** [comment]
Thanks! Will do so.
