### ISSUE TITLE
Misleading Statistics - Build Times

### ISSUE THREAD

**Issue by AndGasper** [parcel-bundler/website#378]
It is misleading to report parcel bundling times with caching and not report the bundle times for equivalent bundlers.

**Comment by DeMoorJasper** [comment]
The benchmark mentions webpack, browserify and Parcel. Not sure what else you'd want?

Updating the benchmarks will probably happen with the Parcel 2 release, but it's just an indicator as it depends heavily on what the codebase you run the benchmark on looks like. It's the same for bundle sizes, some are smaller in Parcel, some are not

**Comment by chrisfitkin** [comment]
Would it make sense to also include webpack with caching as a reference point if you’re comparing the bundle times to Parcel with caching?

**Comment by DeMoorJasper** [comment]
@chrisfitkin webpack has no caching?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AndGasper** [comment]
I will have to dig a little deeper into the extent of Parcel's scope, but the misleading aspect is if Parcel's assertion as the appropriate bundling tool is related to how it handles compilation, then an incomplete reporting of observed values is, perhaps misleading was too strong a term but, _asymmetric_. 

Could you link me to the configs used to get those stats?
