### ISSUE TITLE
--no-cache isn't working(?)

### ISSUE THREAD

**Issue by xphstos** [parcel-bundler/website#392]
Hi, 
I'm trying to disable the .[hash].ext before each file.
If I'm not mistaken that should be possible with `--no-cache` flag but it doesn't work.
Am I wrong?

I've tried
```bash
parcel build src/index.pug --no-cache --no-minify
```
But I had no luck.
Same thing with with serve .

Parcel ver.: 1.10.3
Node ver.: v10.5.0
NPM ver.: 6.8.0
Yarn ver.: 1.13.0
OS: macOS Sierra 10.12.6

**Comment by mischnic** [comment]
No, you're looking for `--no-content-hash`. But it's missing in the docs...

If you're still having issues with parcel itself, please open an issue here: https://github.com/parcel-bundler/parcel
