### ISSUE TITLE
Error no entries found  

### ISSUE THREAD

**Issue by insaneFreak** [parcel-bundler/website#396]
I have problem with comand line when i wrote "parcel index.html" its shows me:
×  No entries found.
    at Bundler.bundle (C:\Users\insanity\AppData\Roaming\npm\node_modules\parcel-bundler\src\Bundler.js:261:17)
    at <anonymous>

C:\xampp\htdocs\task-frontend>npm run dev

> task-frontend@1.0.0 dev C:\xampp\htdocs\task-frontend
> parcel *.html

Please help why this happens to me ?

**Comment by mischnic** [comment]
> Please help why this happens to me ?

This happens when the entry file you specified (`index.html` in your case) doesn't exist.

**Comment by insaneFreak** [comment]
Ok now i added but drops another error
×  C:\xampp\htdocs\task-frontend\index.html: Cannot read property 'walk' of null

**Comment by mischnic** [comment]
`C:\xampp\htdocs\task-frontend\index.html` seems to be empty?

**Comment by insaneFreak** [comment]
Yes. ok i figured out it should be not empty..

**Comment by mischnic** [comment]
This error is fixed in the next release of parcel.

**Comment by XavierTwitty** [comment]
I having a problem running a start script I created 
"start" : "parcel src/index.html" 
I have a script tag in my index.html
<script src="index.js" defer><script>
when I run npm run start I get no entries found I tried uninstalling/ re-installing and updating npm but I getting the same result

**Comment by XavierTwitty** [comment]
I having a problem running a start script I created
"start" : "parcel src/index.html"
I have a script tag in my index.html
<script src="index.js" defer><script> when I run npm run start I get no entries found I tried uninstalling/ re-installing and updating npm but I getting the same result

**Comment by towry** [comment]
Fixed by `rm -rf node_modules && npm i`.
