### ISSUE TITLE
Parcel not getting executed

### ISSUE THREAD

**Issue by vishank97** [parcel-bundler/website#423]
Whenever I try to execute my "index.html" file of my project using "parcel index.html" it gives an error stating that _**The term 'parcel' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.**_
Please help me with this problem.

**Comment by Taym95** [comment]
Hi, this issue has nothing to do with parcel documentation, you probably need to ensure that parcel is installed in your machine, and its good if you check StackOverflow.

**Comment by DeMoorJasper** [comment]
Please follow the getting started guide. It tells you to install it either globally to have it in the commandline or run parcel through the package.json scripts.

There might be some other issue causing this. However these will be unrelated to Parcel and more likely be related with your yarn/npm install.

https://parceljs.org/getting_started.html
