### ISSUE TITLE
PostHTML documentation is very poor

### ISSUE THREAD

**Issue by kwhat** [parcel-bundler/website#434]
The HTML documentation doesn't really tell me how to do anything with PostHTML and Parcel that doesn't involve an HTML entry point.  For example, how do you use [PostHTML-Extend](https://github.com/posthtml/posthtml-extend) with Parcel?  Do I just shovel the Javascript to create the HTML file in my entry point?  I am very confused.

**Comment by DeMoorJasper** [comment]
`posthtml-extend` is a plugin so it should be defined in `.posthtmlrc ` or `posthtml.config.js ` as said in the docs.

https://en.parceljs.org/html.html#posthtml

**Comment by kwhat** [comment]
Yes, I got that part, however, I still do not understand how to replace `<block` tags with their substitute content.  Do I need to run `babel-node posthtml-extend-compile.js` with the JS outlined in https://github.com/inside-demo/posthtml-expression-demo/blob/master/index.js ?

**Comment by DeMoorJasper** [comment]
@kwhat that should all be part of posthtml config as far as I can see

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kwhat** [comment]
Best I can tell, this is not possible as it is a chicken and egg type issue.  I can get posthtml-extend to work if I use the posthtml.config.js and put the javascript to run from index.js in there, but there is still no reliable way to create the html files via posthtml-extend and then pass those files to parcel.  Besides running `babel-node index.js && parcel build dist/*`, I am out of ideas about how to make this work.  I guess i'll keep looking for yet another tool or just do this in bash+sed in 15 min.

**Comment by DeMoorJasper** [comment]
I have no clue why you'd need JS for this tbh.

This should work
```JSON
{
  "plugins": {
    "posthtml-extend": {
    	encoding: 'utf8',
    	root: 'templates'
	},
    "posthtml-expressions": { 
		locals: { 
			className: 'intro', 
			name: 'Marlo',
			foo: 'bar'
		}
	},
"posthtml-beautify": {}
  }
}
```
