### ISSUE TITLE
The search doesn't work

### ISSUE THREAD

**Issue by smellyshovel** [parcel-bundler/website#440]
Steps to reproduce:

1. Go here: https://en.parceljs.org/getting_started.html
2. Type "images" in the search bar
3. Click on the first result ("Images in JSX")

Should open the respective docs page (I guess), but instead redirects to https://parceljs.org/#images-in-jsx

![Peek wefwef05-14 20-02](https://user-images.githubusercontent.com/9782236/57717305-9db21d80-7683-11e9-826c-100557864fcb.gif)

**Comment by DeMoorJasper** [comment]
It does work, but the algolia docsearch config is a little incorrect I think.
It assumes english is at `parceljs.org` while that's not always the case. I'll look into fixing it.

**Comment by DeMoorJasper** [comment]
This should fix it afaik https://github.com/algolia/docsearch-configs/pull/845
I'm no expert at algolia's config files, but it should fix it afaik.

**Comment by mischnic** [comment]
Seems fixed
