### ISSUE TITLE
Make reviewer per languages

### ISSUE THREAD

**Issue by item4** [parcel-bundler/website#45]
I'm working on ko-KR translation. But I'm not sure is my translation correct. I need reviewer for ko-KR translation.

Maybe other worker also needs reviewer. I think we must need at least 2 reviewers per languages.

and I think we needs slack channel for converstation between translators. for example, ko-KR translator need `#website-ko`

**Comment by brandon93s** [comment]
Hello @item4, feel free to present this idea in slack. 

As a general rule, I'd recommend only working on translations thatbthe contributor speaks fluently.
