### ISSUE TITLE
CLI Docs: Note that --no-content-hash is only for js files

### ISSUE THREAD

**Issue by bbonet** [parcel-bundler/website#457]
This is for the CLI section. Although it's in the sample code, it might be worthwhile noting that --no-content-hash only works when a javascript file is passed build.

**Comment by mischnic** [comment]
>  --no-content-hash only works when a javascript file is passed build.

What do you mean by that? `--no-content-hash` doesn't remove the hash from the filename. It only makes it not change between builds.
Entrypoints (e.g. what you pass to to `parcel build ...`) are never hashed, regardless of that flag.

**Comment by bbonet** [comment]
Oh! Okay I understand. So if I use index.html with build it will work? In
my experience today it does not. Maybe I'm doing something wrong.

**Comment by mischnic** [comment]
Running `parcel build src/index.html` might create these files:
```
dist/index.html
dist/style.28ea8f.css
dist/main.af820be.js
dist/logo.cb398ef.png
```
