### ISSUE TITLE
API documentation unclear

### ISSUE THREAD

**Issue by katsar0v** [parcel-bundler/website#494]
Hello guys, I stumbled upon the API documentation clear, because `Parcel` has no config. But what is this API, how should it be used, in `gulp` or? 

There are some javascript lines, but there is no real example for the API usage.

**Comment by DeMoorJasper** [comment]
https://parceljs.org/api.html explains the node api.

It's just node.js so you can use it with wathever

**Comment by katsar0v** [comment]
Okay maybe an example or explicit info that this is about node.js would be helpful, there are a lot out there that use npm without knowing node.js specifics. A full cycle example would be even better : file create, file save and naming, file execution and result documentation for the example

**Comment by joeyhub** [comment]
The API is meant to be used programmatically however you like but it isn't well documented and possibly has design issues.

It would be great if the API bundle explains how to just bundle something without getting mixed up with CLI.

I just want:

```const bundle = await bundle(entrypoint);```

Where I can say start with a JS file and don't give me HTML or output to the file system.

The bundle might have the JS and CSS and that's it or even a single JS with a CSS loader.

Instead the API doc gives a library description that makes more sense for CLI than proper programmatic use.

The point of people using an API is going to be to give them the flexibility to do what they want (IE, make it a part of gulp though it seems redundant).

Instead it's tightly coupled with a few concerns like express and CLI.

**Comment by ericmorand** [comment]
@joeyhub the API documentation is definitely lacking. I'm trying to replace browserify by parcel to bundle JavaScript and TypeScript in our own custom development platform and it's still unclear how we can do something as basic as writing the bundles to the filesystem once they are generated.

And yes, the API themselves look like they are very opinionated:

* There is an express middleware
* There are minifying options
* There is a dev server
