### ISSUE TITLE
How to stop HTML comments being removed on build

### ISSUE THREAD

**Issue by HenryBrown0** [parcel-bundler/website#499]
When building my application all HTML comments are removed.

I've tried searching the docs and couldn't find anywhere stating that comments are removed at build.

For example, this comment would be removed:

```html
<!-- BODY -->
```
----------
### Some context
I'm trying to server-side render a ReactJS application which I would replace this comment with. I realise I could use a string like 'replace-me' but it seems a hack around and may get messy down the road.

### The question
How would I keep HTML comments after building my application?

**Comment by kwelch** [comment]
This should probably be a bug on parcel-bundler/parcel, not the website. 

Could you re-create there with repro steps and versions, please?

**Comment by HenryBrown0** [comment]
@kwelch Will do 😄 , wasn't sure if it was just missing docs

**Comment by HenryBrown0** [comment]
Creating a .htmlnanorc file solved this issue.
```json
{
  "removeComments": false
}
```
Might be worth adding this to the website if it isn't already
