### ISSUE TITLE
Getting started docs - demo repo

### ISSUE THREAD

**Issue by TheJaredWilcurt** [parcel-bundler/website#511]
There's a lot of steps on the getting started guide and it's pretty messy with all of the yarn duplication.

It would be nice if right at the top there was a big ass button that just said "See a hello world demo repo". That would link to a repo with the package.json, and scripts and files already set up.

**Comment by DeMoorJasper** [comment]
We could probably use GitHub's template repositories for this.

https://help.github.com/en/articles/creating-a-template-repository

**Comment by kwaimind** [comment]
Is this still an active issue? I'd be happy to generate a project using the https://createapp.dev/parcel app, tweak it a little and submit a PR.
