### ISSUE TITLE
Add some documentation about debugging in VSCode with Debugger for Chrome

### ISSUE THREAD

**Issue by arnavb** [parcel-bundler/website#521]
For the people who do JS development, VSCode is a very commonly used editor. One of the things that's important while writing code is debugging, and the Parcel website provides no information on how to debug in VSCode. 

Having to find this out myself recently, I went to google and stumbled upon this issue: https://github.com/parcel-bundler/parcel/issues/611, specifically [this comment](https://github.com/parcel-bundler/parcel/issues/611#issuecomment-385986345) which contains a working configuration for source maps.

I think that instead of having users search for this information in an obscure Github issue, it should be canonically included in the Parcel docs.

This is the working `launch.json` I'm using:

```json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:1234",
      "webRoot": "${workspaceFolder}",
      "breakOnLoad": true,
      "sourceMapPathOverrides": {
        "../*": "${webRoot}/*"
      }
    }
  ]
}
```

My folder structure is:

```
├── dist
│   ├── bundle.4fb5d41c.js
│   ├── bundle.4fb5d41c.js.map
│   └── index.html
├── package-lock.json
├── package.json
├── src
│   ├── index.ts
│   ├── index.html
└── tsconfig.json
```

If you guys want, I can create a PR adding this to the docs.

**Comment by arnavb** [comment]
@mischnic Can I create a PR adding this info?

**Comment by mischnic** [comment]
Sure, maybe on "Getting Started"?
