### ISSUE TITLE
Add documentation safe-write

### ISSUE THREAD

**Issue by DeMoorJasper** [parcel-bundler/website#53]
The file watcher gets buggy when used inside an environment that utilises safe write like gedit on ubuntu and some other editors, we should document this so people don't run into this issue presuming it's a Parcel bug.

We tried to detect this automatically, but with no luck so far, related issues:
https://github.com/parcel-bundler/parcel/issues/221
https://github.com/parcel-bundler/parcel/pull/238

**Comment by davidnagli** [comment]
Do we have any updates on this?

**Comment by DeMoorJasper** [comment]
Made a PR for it :) (Only english version though as that's the only doc language i understand)
