### ISSUE TITLE
Request a new campagin?

### ISSUE THREAD

**Issue by faergeek** [parcel-bundler/website#536]
<img width="1581" alt="изображение" src="https://user-images.githubusercontent.com/3524621/68641942-7c8c9580-051d-11ea-8fb2-93995b1578bc.png">

Can you fix this, please? :-)

**Comment by devongovett** [comment]
@faergeek yeah we can probably do that. I'll reach out to the folks at Cotton Bureau.

In the meantime, I do have some extras. If you donate $25 on opencollective.com/parcel and DM me your size (M or L) and address on Twitter I'll mail you one! 😄

**Comment by faergeek** [comment]
@devongovett No money, no hurry 😄 I'll wait for upcoming month 👍
