### ISSUE TITLE
when bundle the ejs template file, if throw error

### ISSUE THREAD

**Issue by keiouks** [parcel-bundler/website#549]
I use template file ejs in my project, but parcel throw error

```
<header class="ui-sidebar-header">
    <img class="ui-header-logo" src="<%=data.sysIconUrl%>" alt="logo">
    <span class="ui-header-name"><%=data.systemName%></span>

    <div class="ui-header-loginout">
        <i class="iconfont icon-arrow01-down"></i>

    </div>
    <a href="javascript:;" class="ui-header-loginBtn ui-hide">退出</a>
</header>
```

as you can see, the img src property should inject from nodejs server side, what can i do for it

**Comment by DeMoorJasper** [comment]
This is not an issue with the documentation, feel free to open a new issue here: https://github.com/parcel-bundler/parcel if this still is an issue with PArcel 2, sorry for the late reply
