### ISSUE TITLE
ReasonML getting started docs required one extra install

### ISSUE THREAD

**Issue by mrispoli24** [parcel-bundler/website#562]
I just ran through getting setup with the ReasonML example provided and in order to get it to properly run I needed to `yarn global add reason-cli@latest-macos`. I thought the first step of installing the `bs-platform` would do the trick but I still got the following error when running:

`Fatal error: exception Unix.Unix_e
rror(Unix.EEXIST, "mkdir", ".../reasonml-demo/lib")`

I think the above should be added to the docs for mac users. Not entirely sure how this would play out when deploying.

**Comment by DeMoorJasper** [comment]
not yet supported in parcel 2 so gonna close this
