### ISSUE TITLE
Translate parcel.org into Spanish

### ISSUE THREAD

**Issue by dgrizzla** [parcel-bundler/website#57]
Hi, I haven't found any issue related to spanish docs, so I've decided to team up with @albizures to translate the site.

**Comment by devongovett** [comment]
Awesome, let me know if you need anything!

**Comment by lrn2prgrm** [comment]
@dgrizzla, I could colaborate. let me know if you want to assign some files to me so I can for your fork and send you some PRs. I will write to your email too.

**Comment by clarksandholtz** [comment]
I'd love to help if there is still work to be done!

**Comment by dgrizzla** [comment]
@clarksandholtz sounds great! There are some files that still need to be translated, check out the repository and hit me up with the files you're gonna change. Thanks in advance!

**Comment by devongovett** [comment]
Is this PR related to the work going on here? https://github.com/parcel-bundler/website/pull/81

**Comment by dgrizzla** [comment]
@devongovett not at all

**Comment by devongovett** [comment]
Hmm, ok @kidandcat would be good if you could collaborate with @dgrizzla and others here.

**Comment by devongovett** [comment]
And next time please do check the issues to see if someone is already working on it. That way we don't duplicate work.

**Comment by kidandcat** [comment]
@devongovett Sorry, didn't even notice there was something going on.

**Comment by kidandcat** [comment]
UP
This is going out of control. There are now 2 PR for a full Spanish translation, has it been any of you?

**Comment by gnapse** [comment]
No, sorry, I too started working on this with a couple of colleagues. I mentioned it around, but did not check for issues like this one. So it's three efforts so far, and two of them out on PRs (none of which apparently are from the creators of this issue). Sorry!

**Comment by devongovett** [comment]
Done!
