### ISSUE TITLE
Asset Types manual page doesn't make it clear where should I register an Asset Type

### ISSUE THREAD

**Issue by awvalenti** [parcel-bundler/website#572]
https://en.parceljs.org/asset_types.html says `You can register your asset type with a bundler using the addAssetType method` and shows some code:
```javascript
const Bundler = require('parcel-bundler')

let bundler = new Bundler('input.js')
bundler.addAssetType('.ext', require.resolve('./MyAsset'))
```

But where should I put that code?

**Comment by mischnic** [comment]
Are you creating a plugin and want to use the Parcle CLI? Do something like this in your plugins's entry point: https://github.com/DeMoorJasper/parcel-plugin-svelte/blob/master/packages/parcel-plugin-svelte/lib/main.js

**Comment by awvalenti** [comment]
I wanted to make a loader for binary/text files. I tried simply loading it, but got a strange result. Instead of giving me the file contents as string or buffer, the result of reading the file was a string containing the generated filename after building it:
![image](https://user-images.githubusercontent.com/834921/76161220-fa4d6000-610f-11ea-838d-09ec70827494.png)

I thought maybe writing a plugin would solve the problem, despite the fact that the above situation seemed like a bug to me.

**Comment by mischnic** [comment]
>  the result of reading the file was a string containing the generated filename after building it:

That is the default behaviour, meaning that your plugin isn't running.

You need to create a `parcel-plugin-...` package that registers an asset type as I linked above.
