### ISSUE TITLE
Assign new/custom extension to HTML asset type

### ISSUE THREAD

**Issue by kravemir** [parcel-bundler/website#573]
I would like to assign a new extension to HTML asset type, which would be `.gohtml`, because:

* Goland IDE automatically add autocompletion for golang templates for files with `.gohtml` extension,
* I've got some `assets/layouts/master.gohtml` file with base layout and resource (CSS+JS) links.

Currently, I've got the project setup with webpack,.. and, I would like to migrate it to parcel (as I've used in on different project, and I like it more). However, this issue is quite a blocker.

It seems to be just easy configuration issue, but I've read [HTML docs](https://parceljs.org/html.html) and [Asset Types](https://parceljs.org/asset_types.html), and I've got no clue from these docs, how can I register custom extension for HTML asset type. Maybe, section called _Assign Custom Extension To Existing/Standard Asset Type_ with example would be helpful.

And, honestly, I don't see myself (others) spending hours by studying parcel internals to get this simple configuration done.

**Comment by mischnic** [comment]
Plugin code:
```js
module.exports = function(bundler) {
  bundler.addAssetType('gohtml', require.resolve('parcel-bundler/src/assets/HTMLAsset.js'));
};
```

**Comment by kravemir** [comment]
@mischnic thank you for the answer. So, I need to create, publish, and install a new plugin (according to [docs](https://parceljs.org/plugins.html))?

> Using plugins in Parcel could not be any simpler. All you need to do is install and save them in your package.json

Or, is there something like `parcel-config.js` ?

**Comment by mischnic** [comment]
> So, I need to create, publish, and install a new plugin (according to docs)?

Yes

> Or, is there something like parcel-config.js ?

With Parcel 2, all you need is a `.parcelrc`:
```json
{
	"extends": ["@parcel/config-default"],
	"transforms": {
		"*.gohtml": ["@parcel/transformer-posthtml", "@parcel/transformer-html"]
	}
}
```

**Comment by kravemir** [comment]
> > So, I need to create, publish, and install a new plugin (according to docs)?
> 
> Yes

Well, that's far from "Using plugins in Parcel could not be any simpler.",... as it can be simpler - provide way to include local js file (ie. for tiny customization of self-contained private project).

> > Or, is there something like parcel-config.js ?
> 
> With Parcel 2, all you need is a `.parcelrc`:
> 
> ```json
> {
> 	"extends": ["@parcel/config-default"],
> 	"transforms": {
> 		"*.gohtml": ["@parcel/transformer-posthtml", "@parcel/transformer-html"]
> 	}
> }
> ```

Sounds useful. Definitely a good way forward!

However, I encountered second issue,.. parcel packs all resources into single output directory,.. And, I need to store assets/resources in separate directory to setup rule for serving of static assets. As, it's not SPA, but regular website (friendly to no-javascript users/browsers), where pages are rendered by server written in go. So,.. maybe there'll be more issues, and for now, I'll stick with webpack, and I'll give it try later with parcel 2 or later.

**Comment by mischnic** [comment]
> Well, that's far from "Using plugins in Parcel could not be any simpler.",... as it can be simpler - provide way to include local js file (ie. for tiny customization of self-contained private project).

(Using a monorepo works)
But just saying: "*Using* plugins in Parcel could not be any simpler."
