### ISSUE TITLE
Bundler API Question

### ISSUE THREAD

**Issue by brendonmatos** [parcel-bundler/website#577]
So, I`m having some difficulty to use the Bundler API...

The code above is working, but the last line is what i need
```javascript
const Bundler = require('parcel-bundler')
const entryPath = path.join(component);

const bundler = new Bundler(entryPath, {
	target: 'node',
	minify: true,
	bundleNodeModules: true
})

const bundle = await bundler.bundle()

// What i need
// response.send( bundle.generated.js )
```

I looked in the documentation and I didn't find any reference that could help this implementation
Does Parcel have an method to get the same content that writes in the file dist/Output.js?

Thanks!

**Comment by mischnic** [comment]
> Does Parcel have an method to get the same content that writes in the file dist/Output.js?

No

**Comment by brendonferreira** [comment]
Thanks for the quick answer!

Would you find it interesting to implement something like that? I would be willing to implement it

**Comment by mischnic** [comment]
Is there a reason you don't simply read the bundle from the file system?

**Comment by bridgeToVillage** [comment]
Which file does the content exist in？No one asked?

**Comment by DeMoorJasper** [comment]
We're no longer doing updates to parcel 1 so gonna close this
