### ISSUE TITLE
What is assets/icons.js for?

### ISSUE THREAD

**Issue by Loksly** [parcel-bundler/website#582]
Hi everyone!

I'm trying to use the [website](https://parceljs.org/) but somehow the script on https://github.com/parcel-bundler/website/blob/master/src/assets/icons.js is trying to make useless requests consuming both CPU, memory and bandwith for nonsense. Because of that CPU gets stuck and the user experience is poor.

![parcel_icons_js](https://user-images.githubusercontent.com/1235649/78883462-d5734200-7a59-11ea-838d-7a5663a7606f.png)
![parcel_network](https://user-images.githubusercontent.com/1235649/78883466-d6a46f00-7a59-11ea-8505-5bd14340acad.png)

Please consider changing or removing that code.

have a nice day!

**Comment by DeMoorJasper** [comment]
You can always just go directly to the docs part of the site. I don't really see any real performance issues with the icons script.

https://parceljs.org/getting_started.html
