### ISSUE TITLE
Scrollbar for parcel website

### ISSUE THREAD

**Issue by Caleb335** [parcel-bundler/website#587]
I discovered that the scrollbar on the parcel website is the conventional one that isn't styled, I'd love to work on that

**Comment by devongovett** [comment]
I don't think it's really possible to style scrollbars cross browser. Plus, people expect their scrollbars to match their OS, so I don't really think it's a good idea anyway.

**Comment by Caleb335** [comment]
I've actually styled scrollbars before, and they work fine...

But since you said it isn't a good Idea, no probs 🙂
