### ISSUE TITLE
Questions about using Vue

### ISSUE THREAD

**Issue by locness3** [parcel-bundler/website#589]
When using Vue with Parcel :
1) Why is the vue instance not attatched to a variable?
2) What's the `render` property, and how does it work?

**Comment by DeMoorJasper** [comment]
There's vue support here: https://v2.parceljs.org/languages/vue/

If you have a question about how parcel works you'll probably have more luck in the parcel repository as this repository is for documentation. See https://github.com/parcel-bundler/parcel/discussions
