### ISSUE TITLE
Move to Cloudflare for CDN

### ISSUE THREAD

**Issue by ryanworl** [parcel-bundler/website#59]
Right now the website is hosted from two IPs in AWS us-west-1 in San Jose.

This means everyone who wants to see the website around the world has to make requests all the way to San Jose, and the project is paying for AWS bandwidth, which is expensive.

The free tier of Cloudflare would fix both of these. Or any other CDN, I suppose, but it wouldn't be free.

**Comment by shawwn** [comment]
Sounds like David just volunteered to do this. Good luck, I believe in you!

**Comment by davidnagli** [comment]
ahaha thanks! 🤔 😂

**Comment by devongovett** [comment]
website is using zeit now, not aws directly. zeit should be distributing things around the world automatically. see https://zeit.co/world

**Comment by ryanworl** [comment]
That Zeit World thing appears to be a DNS service. While I’m sure it is fine, querying from a DNS server in Philadelphia (where I am) and the UK (for example) returns the same set of AWS IPs.

Unless I made a mistake here, even if the DNS is distributed, the servers hosting the content are not.

**Comment by TimNZ** [comment]
Sneaky use of this issue to segway  into recommended recipe for cache busting file name generation and deployment.

Production builds utilise the filename of the relative path e.g.
```
<script src='./index.js'></script>
```
results in an index.js being generated, and other assets using a hash strategy for filenames.

I had a look at posthtml, that has a posthtml-cache plugin that generates uses a query string strategy to modify links, whereas I want a generated filename.

If I have a single publicUrl e.g. https://cdn/assets, will the generated filename hashes of assets ever result in conflicts in different builds which will result in browser caching serving an old version of an asset?
If not, I can optimise uploading of assets to only upload files that doesn't already exist in the CDN.

Thanks for any insights you can provide.
I don't have a lot of experience in CDN/deployment.

Anything Parcel can do to simplify this, or provide Recipes/Guides, is a big step up from everyone else leaving it to devs to figure out through pain.

**Comment by devongovett** [comment]
Just enabled zeit's new cdn, which uses cloudflare under the hood. https://zeit.co/blog/now-cdn
