### ISSUE TITLE
very basic question about "build"

### ISSUE THREAD

**Issue by pablonolla** [parcel-bundler/website#591]
Hi 

I'm not a developer, not familiar with many of the tools and procedures most of you surely take for granted,  but i still hope the question would be understandable and someone out there would give me a hint. Sorry for the length of this.

I make publications (mostly books) for print and screens with XHTML and CSS... and also use some JS libraries.
On top of PDF and ePub, for each book I generate what i call a "WebPublication", which is basically a folder containing an index.html and several folders called "images", "css", "js" and "fonts".  With this, the book can be read on any browser and enjoy some "web friendly" features like popup footnotes, dynamic table of contents and so on. 
I don't use React or any other framework. 
  
Until now i've been uploading the whole project folder, as it is, to the server. 
But i guess it would be better to minify the project and generate a more efficient package to upload. And I've stumbled upon Parcel... 

Following the "Getting started" page I've installed Parcel, added a .json file to the project folder...  All good. Typing "parcel my_content.html" in the Terminal it creates a local host... 
But when i get to Production, I don't understand the "parcel build" instruction. 
If i pass "my_content.html" file to it, it actually generates a "dist" folder containing all of the files, minified, with a string of charters added to the original filename, all their "css.map" files... 
but in that folder "my_content.html", even though it's minified and has new relative paths to the new css, images and js files, opens in the browser without any css or js applied.

Am I missing something or doing something wrong?  

Should i have something written on the json file (apart from what "npm init -y" generate by default)?

Is it an  "index.js" file needed somewhere?

Thank you for reading this extremely long question. 

And thank you for sharing your work. 

All the best!

p

**Comment by mischnic** [comment]
> But i guess it would be better to minify the project and generate a more efficient package to upload. And I've stumbled upon Parcel...

I don't know which JS libraries you are using, but I don't think there is much benefit to using a bundler in your situation.

> folder containing all of the files, minified, with a string of charters added to the original filename,

At this point, it's not possible to change that.

**Comment by pablonolla** [comment]
Thanks for answering!
