### ISSUE TITLE
Best way to pick swc over Babel for JS compilation?

### ISSUE THREAD

**Issue by unquietwiki** [parcel-bundler/website#594]
I find Parcel to be amazing, especially in comparison to setting up a Webpack environment. One question: I was made aware of [swc, a high-speed Rust-based JS-compiler](https://swc-project.github.io/), that is Babel-CLI compatible. It's somewhat unclear how I'd get Parcel to use that over Babel. The [packagers page](https://parceljs.org/packagers.html) gives some clue about how this might be doable.

Thanks!

**Comment by mischnic** [comment]
Even if you replaced the transformation (babel-preset-env) with swc, Parcel still uses Babel internally. We might investigate this with Parcel 2.

See https://github.com/parcel-bundler/parcel/issues/2593

**Comment by unquietwiki** [comment]
Thanks!!!
