### ISSUE TITLE
Need to load the animation plugin for ScrollMagic and GSAP

### ISSUE THREAD

**Issue by erickespinoza** [parcel-bundler/website#597]
I'm trying to use those npm repositories:

- https://www.npmjs.com/package/gsap
- https://www.npmjs.com/package/scrollmagic

but those libraries also required a scrollmagic plugin called animation that will be this code: https://github.com/janpaepke/ScrollMagic/blob/development/scrollmagic/uncompressed/plugins/animation.gsap.js

how I made to load this dependencies with Parcel?

thanks,
Erick Espinoza

**Comment by SarthakDandotiya** [comment]
You can get rid of ScrollMagic completely as GSAP now has a plugin called [ScrollTrigger](https://greensock.com/scrolltrigger/) which can be used instead to do the similar things ScrollMagic was used for.

Not exactly the solution to you might need but it should help anyway :)

**Comment by mischnic** [comment]
This is not related to the Parcel website. If you still have propblems, please open an issue here: https://github.com/parcel-bundler/parcel/issues
