### ISSUE TITLE
Extend documentation import .scss into TypeScript

### ISSUE THREAD

**Issue by skewty** [parcel-bundler/website#600]
The docs don't yet include an example of how to import into TS.

`import './foo.scss'` works if you don't need to refer to it, but what if I need to refer to the styles
like in a web component for example?

`import * as css from './foo.scss'` does not work

**Comment by fayismahmood** [comment]
https://adrianhall.github.io/javascript/react/2020/03/29/parcel-typescript-react/

**Comment by skewty** [comment]
I don't thinking React creates / uses [Web Components](https://developer.mozilla.org/en-US/docs/Web/Web_Components).  I am referring to modern technology libraries like lit-Element.

I want to import a SCSS file that gives me a string of the CSS.

Webpack has [lit-scss-loader](https://github.com/drdreo/lit-scss-loader) which allows importing like this:
```js
import Style1 from './style-1.scss';
```

I basically want to do the same in a TS file.

**Comment by mischnic** [comment]
You mean importing a style as text?
That's possible with Parcel 2: https://parcel2-docs.now.sh/configuration/plugin-configuration/#predefined-(offical)-named-pipelines (that link might change in the future)

**Comment by skewty** [comment]
### src/my-element.ts
```ts
import {LitElement, html, customElement, property, css} from 'lit-element';

// @ts-ignore
import style from "bundle-text:./my-element.scss"

@customElement('my-element')
export class MyElement extends LitElement {
  static styles = css`${style}`;

  @property()
  name = 'World';

  render() {
    return html`<h1>Hello ${this.name}!</h1>`;
  }
}
```
### src/index.html

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello Lit-Element</title>

</head>
<body>
    <script type="module" src="./my-element.ts"></script>
    <my-element name="lit-Element"/>
</body>
</html>
```
### src/my-element.scss
```scss
h1 { color: green }
```

### Output

```
[scott@localhost parcel-typescript-lit-element]$ npx parcel ./src/index.html
Server running at http://localhost:1234 
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "bundle-text:.": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/scott/.npm/_logs/2020-06-16T16_27_36_092Z-debug.log
🚨  /home/scott/Projects/parcel-typescript-lit-element/src/my-element.ts:9:18: Failed to install bundle-text:..
    at PromiseQueue.install [as process] (/home/scott/Projects/parcel-typescript-lit-element/node_modules/parcel-bundler/src/utils/installPackage.js:46:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I am trying to do what you suggested.  Big thanks for showing me that feature.

How do I enable / use bundle-text?  Do I need to npm install something additional?  
The docs seem to indicate it is built-in.

**Comment by mischnic** [comment]
> How do I enable / use bundle-text? Do I need to npm install something additional?
The docs seem to indicate it is built-in.

Parcel **2** (`yarn add parcel@nightly`)

**Comment by DeMoorJasper** [comment]
Documented in parcel 2?
