### ISSUE TITLE
Add documentation for what the options are available in .sassrc

### ISSUE THREAD

**Issue by GeorgeWL** [parcel-bundler/website#627]
As from reading the page https://parceljs.org/scss.html

all I really know is that there is a config which can be set, but not what the various options for said config file could be.

**Comment by mischnic** [comment]
I think it's these options: https://sass-lang.com/documentation/js-api#options

**Comment by GeorgeWL** [comment]
that's what I mean, it's not made clear.

**Comment by DeMoorJasper** [comment]
is documented here https://v2.parceljs.org/languages/sass/

**Comment by justin-marotta-mavq** [comment]
A default .sassrc would help. Nothing on the site is helping get my .tsx file to recognize a .scss import. @mischnic @DeMoorJasper

**Comment by mischnic** [comment]
Is the error you're getting coming from tsc (= a type error), or an error from Parcel?

**Comment by justin-marotta-mavq** [comment]
@mischnic Thanks for the reply. I believe it is a type error:
`Cannot find module '../styles/App.module.scss' or its corresponding type declarations.ts(2307)`

I've only ever used CSS modules with Next so I'm not sure how to configure them. The app works, it's just a red warning.

SOLVED USING
https://github.com/skovy/typed-scss-modules

package.json scripts:
```
"build": "yarn typed-scss-modules src && parcel build",
"dev": "yarn typed-scss-modules src --w & parcel serve && fg"
```
