### ISSUE TITLE
Document 'target'

### ISSUE THREAD

**Issue by jakearchibald** [parcel-bundler/website#630]
'target' is mentioned in passing on https://v2.parceljs.org/getting-started/configuration/#targets, but it doesn't detail what kind of values it can have, or how it works.

**Comment by mischnic** [comment]
Looks like a link to https://v2.parceljs.org/configuration/package-json/#targets is missing

**Comment by jakearchibald** [comment]
Also, I don't think it's documented that `<script type="module" src=…>` will imply an esm target. I mean, it makes sense, but I don't think it's easy to discover.

**Comment by mischnic** [comment]
Yeah, "Language/HTML" is on the Todo list, which will cover: module/nomodule, inline scripts, inline styles, PostHTML, htmlnano

**Comment by mischnic** [comment]
> Also, I don't think it's documented that <script type="module" src=…> will imply an esm target. I mean, it makes sense, but I don't think it's easy to discover.

https://v2.parceljs.org/languages/html/#dependencies and http://localhost:8080/getting-started/webapp/#differential-serving
