### ISSUE TITLE
"500 Internal Server Error" from parceljs.org

### ISSUE THREAD

**Issue by DariusMontez** [parcel-bundler/website#71]
Today (12/28/17) I went to parceljs.org looking for the docs. Visiting [https://parceljs.org/](https://parceljs.org) returned a 500 error code.

I assume you're already aware of this, but I didn't see an issue for it. I wish I could provide more info, but HTTP error codes don't say much on the client end -

The project looks fantastic, and I'm excited to see what it can do :)

Ubuntu 16.04
Firefox 57

**Comment by brandon93s** [comment]
[https://zeit.co/now](now), which hosts the website, appears to be down.

**Comment by brandon93s** [comment]
The website is back online.
