### ISSUE TITLE
Brazillian Portugese translations are located in Portugese (pt) folder instead of Brazilian Portugese (pt-br)

### ISSUE THREAD

**Issue by wojtekmaj** [parcel-bundler/website#72]
As in title.

Speaking of language dropdowns, I think it definitely shouldn't be "translated", it should have its own place in the code. Ideally, the list could be automatically generated based on available languages. Such code duplication just asks for bugs in the future.

**Comment by wojtekmaj** [comment]
Whoops. Got confused by language codes (flags do not show on Windows). Not really missing Portugese, but marked as Brazillian Portugese. We're gonna have a problem here . There's pt-PT and pt-BR, and these are similar but not identical languages. Folder is called `pt` which suggests pt-PT but it shows Brazillian flag, how come?

**Comment by devongovett** [comment]
the translation is really brazillian portugese but I thought that would be better than english until we got an actual portugese translation.

**Comment by devongovett** [comment]
if you'd like to contribute a portugese translation separate from the brazillian one, feel free! Then we can rename the current one to `pt-br`.

**Comment by wojtekmaj** [comment]
Actually not really (I'm working on Polish translation at the moment), but we should definitely rename this to avoid confusion in the future.

**Comment by Rubemlrm** [comment]
@devongovett i can try help translate to portuguese from portugal =)

**Comment by reebr** [comment]
I don't think that portuguese (from Portugal) should be separated from the brazilian ones. The StackOverflow uses this same model, although the largest number of users are brazilian, the community treats all the questions/answers independent of the native users of other countries that speaks portuguese too.

Countries:
- Angola
- Brazil
- Cape Verde
- East Timor
- Equatorial Guinea
- Guinea-Bissau
- Mozambique
- Portugal
- São Tomé and Príncipe
