### ISSUE TITLE
Numerous accessibility issues on the website

### ISSUE THREAD

**Issue by wojtekmaj** [parcel-bundler/website#75]
* `<h1>` is missing from the page
* `<h2>` is used improperly - text under Parcel logo is just a subtitle, and not actual heading
* Language "dropdown" is not actual dropdown, which makes it impossible for keyboard users to use it.
* Language "dropdown" values are emoji, which are not good for screen readers. If you absolutely have to use emojis, use `<abbr>` tags as well.

**Comment by DeMoorJasper** [comment]
Fixed by #86
