### ISSUE TITLE
Document that there will always be at least one target, even with `main: false`

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/website#759]
This doesn't mean that Parcel will do nothing when running `parcel build src/index.js` but that the default target will be used instead of `main`.
```json
{
  "main": "unrelated.js",
  "targets": {
    "main": false
  }
}
```

https://github.com/parcel-bundler/parcel/issues/5312#issuecomment-721999509

**Comment by AceTheCreator** [comment]
@mischnic is this issue taken by anyone already? if no, then I'd love to take this issue.

**Comment by mischnic** [comment]
Go ahead

**Comment by AceTheCreator** [comment]
@mischnic what do you think? Before I submit a pull request closing this issue.
Before
![parcelone](https://user-images.githubusercontent.com/40604284/98981019-b5d75700-251d-11eb-96c9-a6bba064ca61.png)
After
![parceltwo](https://user-images.githubusercontent.com/40604284/98981092-d1daf880-251d-11eb-810f-bd7720f9dce4.png)

**Comment by mischnic** [comment]
👍
