### ISSUE TITLE
The description of build machine in "Benchmarks" is inaccurate

### ISSUE THREAD

**Issue by jeffhtli** [parcel-bundler/website#77]
The description of build machine in "Benchmarks"  that in the bottom of homepage is inaccurate. I think "quad-core CPU" is better than "4 physical CPUs" .

> Based on a reasonably sized app, containing 1726 modules, 6.5M uncompressed. **Built on a 2016 MacBook Pro with 4 physical CPUs.**

[MacBook Pro - Technical Specifications](https://www.apple.com/macbook-pro/specs/)

**Comment by devongovett** [comment]
Yeah I guess "4 physical cores" would be more accurate. I was trying to distinguish from virtual cores (e.g. hyperthreading). The CPU actually reports 8 cores but only has 4 physical cores. Feel free to make a PR to change the wording.
