### ISSUE TITLE
[RFC] Redesign

### ISSUE THREAD

**Issue by 101arrowz** [parcel-bundler/website#776]
The docs site has many issues, and in my opinion trying to rework the existing 11ty framework to fit Parcel's needs is not practical. Instead, reworking the site to use Parcel + React + MDX would not only provide first-time Parcel users a valuable resource to learn real-world syntax and config, it would allow the developers more control over the webpage. [Even Webpack does this!](https://github.com/webpack/webpack.js.org/blob/master/package.json)

In theory, there are only a few components to create: a splash home page (a la Parcel 1), a collapsible sidebar, a header with search bar, and a content box for the rendered Markdown content. I feel the extra control and full-fledged example to show new users is worth the extra initial development time this may take. The final result will allow an almost identical process for writing the actual content, so after writing the framework there should be no extra development cost.

If the Parcel team believes the aforementioned benefits are worth a total overhaul of the current 11ty framework, I can contribute through PRs. However, right now I think content is a higher priority, so maybe this can be considered after the docs site is complete. Thoughts?

**Comment by mischnic** [comment]
I'm not opposed, but


> Parcel users a valuable resource to learn real-world syntax and
> ...
> the extra control and full-fledged example to show new users is worth the extra initial development time this may take

I don't understand how the build pipeline for the docs has an effect on how useful the end product is (given that it would still be a static website).

> rework the existing 11ty framework 

I'm guessing your main concern are these sample blocks? https://github.com/parcel-bundler/website/blob/v2/src/recipes/react.md#declaring-a-default-export-using-a-function-expression-isnt-recognized


>   content is a higher priority

👍

**Comment by devongovett** [comment]
> reworking the site to use Parcel + React + MDX

We do this for the [React Spectrum](https://react-spectrum.adobe.com/) site in my day job. We have a [custom MDX transformer](https://github.com/adobe/react-spectrum/blob/main/packages/dev/parcel-transformer-mdx-docs/MDXTransformer.js) that compiles MDX to both a server and client bundle (among many other things), and an [optimizer plugin](https://github.com/adobe/react-spectrum/blob/main/packages/dev/parcel-optimizer-ssg/SSGOptimizer.js) that executes the server bundle to produce static HTML. These would require some refactoring, but perhaps this could be made into a more general purpose system? It's definitely nice to write in MDX, and the ability to inject client specific code as well is nice. May be overkill for Parcel given that it's not a client side library, so should be mostly static HTML anyway, but perhaps interesting. We could also just do straight up static HTML/markdown.

> content is a higher priority

definitely.
