### ISSUE TITLE
--no-minify removal missing from the Migration to v2 guide

### ISSUE THREAD

**Issue by avalanche1** [parcel-bundler/website#799]
This CLI command is unsupported in P v2.

**Comment by mischnic** [comment]
I also forgot the API changes here: https://v2.parceljs.org/features/parcel-api/

But I think now you can't specify the default engines without also setting every other option, we should probably allow that (like before the rename)

**Comment by DeMoorJasper** [comment]
@mischnic not sure I'm following all options in defaultTargetOptions are optional as before?

So you can only defined `defaultTargetOptions.engines` and nothing else if you'd want

**Comment by mischnic** [comment]
Oh, I missed the `?` in the flow types 🙈
