### ISSUE TITLE
How are you supposed to use the 'parcelRequire' function in the bundle file generated from TypeScript code?

### ISSUE THREAD

**Issue by peton73** [parcel-bundler/website#811]
The generated bundle file starts with "parcelRequire=function(e,r,t,n)" but I could not find information about how to use it.
I have also tried with Google searches:

> "parcelRequire" site:parceljs.org

> Your search - "parcelRequire" site:parceljs.org - did not match any documents

> parcelRequire site:parceljs.org

(without quotes)

> About 25 results

But I did not find any relevant information when clicking some of those results.

Anyway, I think the webpages should include some documentation about how to use the javascript that parcel generates from typescript.
For example as I did below (but I was not able to use the generated "dist/index.js" to get access to my TypeScript class)

I created a new TypeScript/parcel project in a new empty directory like this:
```
pnpm init -y
pnpm install typescript ts-node parcel-bundler --D
pnpx tsc --init
```

Then added two TypeScript files:
src/classA.ts
```
export default class ClassA {
    getSomethingFromClassAinstance(): string {
        return "string from instance method of class A";
    }
    static getSomethingFromClassAstatic(): string {
        return "string from static method of class A";
    }        
}
```
src/index.ts
```
import ClassA from './classA';
const classA = new ClassA();
console.log(classA.getSomethingFromClassAinstance());
console.log(ClassA.getSomethingFromClassAstatic());
export {ClassA};
```

Then I can execute index.ts as below:
`pnpx ts-node ./src/index.ts`
with the expected output 

> string from instance method of class A
> string from static method of class A

I can also bundle the code into a generated javascript file "dist/index.js" with this command:
`pnpx parcel build ./src/index.ts`

But then **how do I access my TypeScript exported class ClassA from javascript within a webpage?**
I would have expected to be able to use something *similar* like below:
(although I do understand that the specific code below does not work)

index.htm
```
...
<script src="dist/index.js"></script> 

<script>
    var instanceA = new parcelRequire.ClassA();
    document.write(instanceA.getSomethingFromClassAinstance());
    
    document.write(parcelRequire.ClassA.getSomethingFromClassAstatic());
</script>
...
```
I can see in the generated file "dist/index.js" that it contains something that starts with "parcelRequire=function(e,r,t,n)"
So obviously it is a function with four parameters.
Therefore I am not suprised that my sample code above does not work, and also that this would not work:
```
var instanceA = new parcelRequire().ClassA();
```
since the 'parcelRequire' function expects four parameters ... 

But *somehow* I suppose the 'ClassA' should be possible to get access to?

I can also see near the end of the code (within "parcelRequire" in "dist/index.js") that my class 'ClassA' are "exported"(?) with an 'exports' parameter (which is a parameter to a function):
```
... 
"QCba": [function (require, module, exports) {
    ...
    exports.ClassA = t.default;
    var s = new t.default;
    console.log(s.getSomethingFromClassAinstance()),
    console.log(t.default.getSomethingFromClassAstatic());
    ...
```

When I open the above mentioned webpage "index.htm" (which I created manually) that includes the generated "dist/index.js" I can also see that the 'console.log' statement (within 'parcelRequire' in 'dist/index.js') does not become invoked in the webpage by the browser.

This is maybe not very suprising when considering that the code is located within the generated function 'parcelRequire' which never becomes invoked...

However, I would have expected the top-level code (i.e. code outside of any function)
in the "src/index.ts" file to become generated as top-level code, automatically invoked, in the same way as those statements are executed when using 'pnpx ts-node ./src/index.ts' from the command prompt.

I believe that the solution (regarding how to use code generated into the "parcelRequire" function) might have something to do with using something like requirejs, systemjs, commonjs, AMD, UMD, ... but please provide a simple code example of how to get access to the code in the generated "parcelRequire" function.

**Comment by mischnic** [comment]
The `parcelRequire` function shouldn't be called from user code.

There is a `--global something` flag that would set the global variable `something` to the exports of the entry file (Parcel 1).

Otherwise, you could include the `document.write` part in the Parcel build.
