### ISSUE TITLE
ko-KR: translation of "Blazing Fast"

### ISSUE THREAD

**Issue by item4** [parcel-bundler/website#83]
현재 제가 번역한 "불꽃 튀게 빠르고"가 사용되고 있는데, "오지게 빠르고" 가 더 본디 의미에 가깝지 않냐는 지적을 받았습니다.

한국어 번역자분들은 어찌 생각하시는지 궁금합니다.

**Comment by Hazealign** [comment]
젊은 세대에서 가볍게 쓰이고 있는 말이지만, 그래서 더욱 괜찮지 않나 생각해봅니다.
일단 한국어에 "blazing fast"에 해당하는 관용어구가 없어서... 대안으로 적절치 않나 싶습니다.

**Comment by zeakd** [comment]
"오지게" 보다는 좀 더 범용적으로 쓰는 말이 아닌가요. 한 라이브러리를 설명하는 핵심단어인데, 공식문서에 쓰기 적절한 표현은 아닌거같습니다. 굳이 느낌을 살리자면 "눈 깜빡할 새"나 "순식간에", "쏜살같이" 에 가까운 느낌인데, "오지다" 보다는 지금 표현이 낫다고 봅니다.

**Comment by albinotonnina** [comment]
That's just for 'blazing fast'??

**Comment by item4** [comment]
@albinotonnina there is no fitting word for 'blazing fast' in korean.

**Comment by item4** [comment]
@Hazealign @zeakd 단어의 느낌을 살린다는 감각적인 면에서는 '오지게' 라는 단어를 쓰는것도 나쁘지 않아보이지만 zeakd님 지적대로 공식 문서에 저런 급식체(...)를 들이밀어도 되는것인가에 대한 의문이 사라지질 않는군요. 좀 더 많은 논의가 필요하다고 생각합니다. 아무래도 parcel 팀에게 blazing fast의 정확한 뉘앙스를 물어봐야하지 않나 싶군요

**Comment by perhapsspy** [comment]
몇가지 의견 남겨봅니다.

화끈하게 빠르고 설정도 필요 없는 웹 애플리케이션 번들러
끝내주게 빠르고 설정도 필요 없는 웹 애플리케이션 번들러
타오를 정도로 빠르고 설정도 필요 없는 웹 애플리케이션 번들러
타오르는 속도에 설정도 필요 없는 웹 애플리케이션 번들러

**Comment by channprj** [comment]
개인적으로는 앞서 @perhapsspy 님의 표현이나, `매우 빠른` 정도가 낫다고 봅니다. 굳이 `오지다` 라는 급식체(원래는 사투리 표현)를 사용 할 이유는 딱히 없어보입니다. 원래의 표현인 `오달지다` 라는 뜻을 되새겨보아도 `blazing` 과는 그닥 매칭이 되지 않습니다. `오지다` 라는 표현이 아직은 부정적인 인상을 심어 줄 수 있으니 조심히 사용해야 할 것 같습니다.

**Comment by Hazealign** [comment]
화끈하게 빠르다라는 말도 괜찮은 것 같습니다.

**Comment by item4** [comment]
딱히 지배적인 의견의 번역어가 없는 관계로 일단 이슈를 닫습니다.
