### ISSUE TITLE
Improve documentation about the plugin and asset loader APIs

### ISSUE THREAD

**Issue by download13** [parcel-bundler/website#85]
I'm really excited about parcel and would like to create a plugin to compile and load protocol buffer files into a bundle.

The problem is that there doesn't seem to be any documentation of the asset loader API beyond an example of the interface shape.

Even looking through the code of other loaders for help it's not really clear what different calls do and when we might use them.

This leaves anyone who might want to contribute to the parcel ecosystem guessing as to how to do that.

If we could just get a few concrete examples of loaders/packagers/plugins using some common API calls (preferably with a brief explanation) that would be super handy.

Thanks for the cool bundler!

**Comment by xem** [comment]
+1

Even after reading [this tutorial on medium](https://medium.com/@jasperdemoor/writing-a-parcel-plugin-3936271cbaaa), I can't wrap my head around what I can do, concretely, to transform a custom file to a JS function or a CSS snippet.

Also, It's not clear how to test our own plugin locally before sending it on npm, even though [this SO answer](https://stackoverflow.com/questions/52341319/loading-a-local-parceljs-plugin) explains it brievely.

I'd love to see a minimal example in the doc explaining how to do all that.
Thanks!
