### ISSUE TITLE
Bundle Analyzer docs are missing env var step

### ISSUE THREAD

**Issue by jhuleatt** [parcel-bundler/website#881]
I ran 

```shell
parcel build index.html --reporter @parcel/reporter-bundle-analyzer
```

as specified in https://v2.parceljs.org/features/production/#inspecting-bundle-size. However, the `parcel-bundle-reports` folder wasn't created. I had to set the `PARCEL_BUNDLE_ANALYZER` with 

```shell
export PARCEL_BUNDLE_ANALYZER=1
```

as explained in https://github.com/parcel-bundler/parcel/pull/3779#issue-341246387 before it worked.

**Comment by mischnic** [comment]
Looks like you aren't using the latest version of `@parcel/reporter-bundle-analyzer`
