### ISSUE TITLE
Add RSS feed to blog

### ISSUE THREAD

**Issue by canac** [parcel-bundler/website#896]
It would be awesome to add an RSS feed to the Parcel blog so that we can follow along using feed readers.

**Comment by mischnic** [comment]
This shouldn't be hard to implement with https://www.11ty.dev/docs/plugins/rss/ (but the pages in https://github.com/parcel-bundler/website/tree/v2/src/blog should be listed)

**Comment by canac** [comment]
@mischnic Thanks for pointing me in the right direction! Just put together a PR for this.
