### ISSUE TITLE
Problems with Parcel-bundler in the Getting Started Page

### ISSUE THREAD

**Issue by marquesmedina** [parcel-bundler/website#928]
Hi!!

I'm using Parcel and I had a problem regarding using parcel-bundler dependency. The only that I managed to solve it was to install newer dependency named "parcel".

The same happened to other people 
[Click here](https://stackoverflow.com/questions/67069266/parcel-build-error-plugin-is-not-a-function)

Please update your documentation to avoid having these kind of problems.

Regards 
Rippleytrigger

**Comment by mischnic** [comment]
As https://parceljs.org/getting_started.html says:

> Note: This page covers Parcel 1, the documentation for Parcel 2 is being worked on here: v2.parceljs.org

and https://v2.parceljs.org/getting-started/webapp/ indeed uses `parcel`
