### ISSUE TITLE
npm install causes error loop

### ISSUE THREAD

**Issue by ukozdan** [parcel-bundler/website#97]
npm install causes the following: 

$ npm install
npm WARN deprecated fs-promise@1.0.0: Use mz or fs-extra^3.0 with Promise Support

> now@8.5.4 postinstall C:\xxx\xxx\xxx\xxx\website\node_modules\now
> node download/install.js

> For the source code, check out: https://github.com/zeit/now-cli

> Downloading Now CLI 8.5.4 [                    ] 0%
{ Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (zlib.js:142:17) errno: -3, code: 'Z_DATA_ERROR' }
> Downloading Now CLI 8.5.4 [                    ] 0%
{ Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (zlib.js:142:17) errno: -3, code: 'Z_DATA_ERROR' }
> Downloading Now CLI 8.5.4 [                    ] 0%
{ Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (zlib.js:142:17) errno: -3, code: 'Z_DATA_ERROR' }
> Downloading Now CLI 8.5.4 [                    ] 0%
{ Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (zlib.js:142:17) errno: -3, code: 'Z_DATA_ERROR' }

**Comment by brandon93s** [comment]
Just tried on a fresh clone and did not have any issues. Looks like the now download server may have been down. Please try again and let us know if you're still experiencing issues.

**Comment by brandon93s** [comment]
I spoke too soon: 

![image](https://user-images.githubusercontent.com/4730164/35256544-5afbe13a-ffc2-11e7-8bf1-d6be819c2b6c.png)
