### ISSUE TITLE
Anyone update https://parceljs.org/recipes/debugging/ ?

### ISSUE THREAD

**Issue by trancephorm** [parcel-bundler/website#972]
Instructions given there about how to make debugging work in VS Code are not working.

**Comment by chhch** [comment]
I had the problem that breakpoints were ignored. After reading https://github.com/parcel-bundler/parcel/issues/611#issuecomment-696487932. I changed the `sourceMapPathOverrides` to `"/__parcel_source_root/*": "${webRoot}/*"`. This launch configuration works for me:

```javascript
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "pwa-chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:1234",
      "webRoot": "${workspaceFolder}",
      "breakOnLoad": true,
      "sourceMapPathOverrides": {
        "/__parcel_source_root/*": "${webRoot}/*"
      }
    }
  ]
}
```

If it also works for others, this may also close #578.

**Comment by padcom** [comment]
This should definitely be in the docs and frankly speaking also in the generator for `launch.json`, because there are overrides for webpack and I think for meteor (why???). So why not have Parcel overrides added there automagically...

**Comment by mischnic** [comment]
So this line that's currently on https://parceljs.org/recipes/debugging should be removed?
```
 `"../*": "${webRoot}/*",`
```

**Comment by padcom** [comment]
Yes, that doesn't make any sense.
