### ISSUE TITLE
Use language codes or names, not flags

### ISSUE THREAD

**Issue by chris-morgan** [parcel-bundler/website#99]
At present, the .language-dropdown is using national flags via emoji, such as 🇺🇸, U+1F1FA REGIONAL SYMBOL INDICATOR LETTER U followed by U+1F1F8 REGIONAL SYMBOL INDICATOR LETTER S. GitHub may replace it with an image here because these emoji are poorly supported; but quite apart from the matter of poor support for the emoji—

[Flags are not languages.](http://www.flagsarenotlanguages.com/blog/why-flags-do-not-represent-language/)

This should be changed to [use the name](http://www.flagsarenotlanguages.com/blog/best-practice-for-presenting-languages/) (e.g. “English”, “한국어”) of the language instead. (You could get away with using the ISO 639-1 code (e.g. “en”, “ko”) too, but it’s not as good as just the name of the language.)

**Comment by devongovett** [comment]
Yeah I kinda just wanted something more visual but I get it. Would be nice if there were icons for languages, flags seemed the closest.

**Comment by calvinf** [comment]
Some countries have 23+ languages.  Languages cross country boundaries as well.

**Comment by DeMoorJasper** [comment]
Fixed by #86
